[FIX] Post merge issue
```
java.lang.NullPointerException: FirebaseCrashlytics component is not present.
	at com.google.firebase.crashlytics.FirebaseCrashlytics.getInstance(FirebaseCrashlytics.java:197)
	at dev.hossain.remotenotify.utils.CrashlyticsTree.log(CrashlyticsTree.kt:19)
	at timber.log.Timber$Tree.prepareLog(Timber.kt:168)
	at timber.log.Timber$Tree.e(Timber.kt:101)
	at timber.log.Timber$Forest.e(Timber.kt:342)
	at dev.hossain.remotenotify.worker.ObserveDeviceHealthWorker.doWork(ObserveDeviceHealthWorker.kt:90)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.mockk.proxy.jvm.advice.MethodCall.call(MethodCall.kt:14)
	at io.mockk.proxy.jvm.advice.SelfCallEliminatorCallable.call(SelfCallEliminatorCallable.kt:14)
	at io.mockk.impl.instantiation.JvmMockFactoryHelper.handleOriginalCall(JvmMockFactoryHelper.kt:96)
	at io.mockk.impl.instantiation.JvmMockFactoryHelper.access$handleOriginalCall(JvmMockFactoryHelper.kt:19)
	at io.mockk.impl.instantiation.JvmMockFactoryHelper$mockHandler$1$invocation$1$1.invoke(JvmMockFactoryHelper.kt:28)
	at io.mockk.impl.stub.MockKStub$handleInvocation$originalPlusToString$1.invoke(MockKStub.kt:235)
	at io.mockk.impl.stub.SpyKStub.defaultAnswer(SpyKStub.kt:15)
	at io.mockk.impl.stub.MockKStub.answer(MockKStub.kt:44)
	at io.mockk.impl.recording.states.AnsweringState.call(AnsweringState.kt:16)
	at io.mockk.impl.recording.CommonCallRecorder.call(CommonCallRecorder.kt:53)
	at io.mockk.impl.stub.MockKStub.handleInvocation(MockKStub.kt:271)
	at io.mockk.impl.instantiation.JvmMockFactoryHelper$mockHandler$1.invocation(JvmMockFactoryHelper.kt:24)
	at io.mockk.proxy.jvm.advice.Interceptor.call(Interceptor.kt:21)
	at dev.hossain.remotenotify.worker.ObserveDeviceHealthWorker.doWork(ObserveDeviceHealthWorker.kt:34)
	at dev.hossain.remotenotify.worker.ObserveDeviceHealthWorkerTest$doWork notifies when alert was sent more than 24 hours ago$1.invokeSuspend(ObserveDeviceHealthWorkerTest.kt:287)
	at dev.hossain.remotenotify.worker.ObserveDeviceHealthWorkerTest$doWork notifies when alert was sent more than 24 hours ago$1.invoke(ObserveDeviceHealthWorkerTest.kt)
	at dev.hossain.remotenotify.worker.ObserveDeviceHealthWorkerTest$doWork notifies when alert was sent more than 24 hours ago$1.invoke(ObserveDeviceHealthWorkerTest.kt)
	at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt$runTest$2$1$1.invokeSuspend(TestBuilders.kt:317)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.test.TestDispatcher.processEvent$kotlinx_coroutines_test(TestDispatcher.kt:24)
	at kotlinx.coroutines.test.TestCoroutineScheduler.tryRunNextTaskUnless$kotlinx_coroutines_test(TestCoroutineScheduler.kt:99)
	at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt$runTest$2$1$workRunner$1.invokeSuspend(TestBuilders.kt:326)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:263)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:95)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:69)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:47)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at kotlinx.coroutines.test.TestBuildersJvmKt.createTestResult(TestBuildersJvm.kt:10)
	at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt.runTest-8Mi8wO0(TestBuilders.kt:309)
	at kotlinx.coroutines.test.TestBuildersKt.runTest-8Mi8wO0(Unknown Source)
	at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt.runTest-8Mi8wO0(TestBuilders.kt:167)
	at kotlinx.coroutines.test.TestBuildersKt.runTest-8Mi8wO0(Unknown Source)
	at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt.runTest-8Mi8wO0$default(TestBuilders.kt:159)
	at kotlinx.coroutines.test.TestBuildersKt.runTest-8Mi8wO0$default(Unknown Source)
	at dev.hossain.remotenotify.worker.ObserveDeviceHealthWorkerTest.doWork notifies when alert was sent more than 24 hours ago(ObserveDeviceHealthWorkerTest.kt:259)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:502)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$2(SandboxTestRunner.java:285)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:104)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)
```

----

The error occurs because Timber is trying to use FirebaseCrashlytics in your unit tests, but FirebaseCrashlytics isn't properly initialized in the test environment. This happens when Timber tries to log through a CrashlyticsTree instance.

Here's how to fix it:

```kotlin
@RunWith(RobolectricTestRunner::class)
class ObserveDeviceHealthWorkerTest {
    // Existing code...

    @Before
    fun setUp() {
        MockKAnnotations.init(this)
        context = ApplicationProvider.getApplicationContext()

        // Mock Timber to prevent FirebaseCrashlytics errors
        val timber = mockk<Timber.Tree>(relaxed = true)
        Timber.plant(timber)

        // Configure default behavior for notification sender
        // ... rest of your setUp code
    }

    @After
    fun tearDown() {
        // Remove all trees to clean up after test
        Timber.uprootAll()
    }

    // Your test methods...
}
```

This solution:

1. Creates a mock Timber.Tree that won't try to use FirebaseCrashlytics
2. Plants this mock tree before each test with `Timber.plant(timber)`
3. Removes all trees after each test to clean up with `Timber.uprootAll()`

The `relaxed = true` parameter for the mock ensures that any method calls on the tree (like `e()`, `d()`, etc.) will just do nothing instead of throwing errors.

This approach allows your tests to run without needing to properly initialize FirebaseCrashlytics, which can be difficult in a test environment.